name: redis_client
version: 0.1.6-dev
authors:
- Demis Bellot <demis.bellot@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Matias Meno <m@tias.me>
- Max Horstmann <max.horstmann@gmail.com>
description: A high-performance async/non-blocking Redis client for Dart.
homepage: https://github.com/dartist/redis_client
dependencies:
  dartmixins: '>=0.0.1 <0.0.2'
